// Auto-generated by: npx supabase gen types typescript --project-id <project-id> > src/lib/supabase/types.ts
// Run this command after creating your Supabase project and applying migrations.

export type Database = {
  public: {
    Tables: {
      families: {
        Row: {
          id: string
          display_id: string
          family_name: string
          preferred_name: string | null
          primary_contact: Record<string, unknown> | null
          secondary_contact: Record<string, unknown> | null
          address: string | null
          billing_prefs: Record<string, unknown> | null
          status: string
          referred_by: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['families']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['families']['Insert']>
      }
      // Additional table types will be auto-generated after running supabase gen types
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
